pipeline {
    agent any
    
    // Define environment variables, especially for AWS credentials
    environment {
        // You should configure these as Jenkins secret credentials
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID') 
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        
    }

    stages {
        stage('Checkout Code') {
            steps {
                // Assuming your Terraform code is in a Git repository
                git url: 'https://github.com/ManoharSankar/EKS_ProductionSystem.git', branch: 'main' 
            }
        }
        
        stage('Terraform Init') {
            steps {
                sh "terraform init"
            }
        }

        stage('Terraform Plan') {
            steps {
                // Run plan and save the output to a file
                sh "terraform plan -out=tfplan"
            }
        }
        
        stage('Terraform Apply') {
            steps {
                // Execute the apply using the previously saved plan file
                sh " terraform apply tfplan"
            }
        }
    }
}